apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: reader-sa
  containers:
    - name: test
      image: bitnami/kubectl
      command: ["sleep", "3600"]