apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
        - name: logger
          image: busybox
          command: ["sh", "-c", "while true; do echo logging from $(hostname); sleep 10; done"]
