apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: mongo:7
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
    volumeMounts:
      - mountPath: /data/db
        name: mongo-storage
        
  volumes:
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: mongo-pvc
