apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: nginx-web
      labels:
        app: demo
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80