apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: demo
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
       - containerPort: 80
      env:
        - name: MONGO_URI
          value: "wasim"
        
          