apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo hello from PVC > /data/test.txt && sleep 3600"]
      volumeMounts:
        - name: my-storage
          mountPath: /data
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc 
